=== navvvs/LAB5_DOM_PARSER/event.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="ChristUniversity">
<xs:complexType>
<xs:sequence>
<xs:element name="User" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="U_email" type="xs:string"></xs:element>
<xs:element name="U_name" type="xs:string"></xs:element>
<xs:element name="U_id" type="xs:integer"></xs:element>
<xs:element name="U_gender" type="xs:string"></xs:element>
<xs:element name="U_type" type="xs:string"></xs:element>
<xs:element name="U_contact" type="xs:integer"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="Ticket" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="T_id" type="xs:integer"></xs:element>
<xs:element name="T_date" type="xs:string"></xs:element>
<xs:element name="T_price" type="xs:integer"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>


<xs:element name="Event" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="Event_id" type="xs:integer"></xs:element>
<xs:element name="Event_name" type="xs:string"></xs:element>
<xs:element name="Event_type" type="xs:string"></xs:element>
<xs:element name="Event_time" type="xs:date"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="Staff" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="Event_manager_id" type="xs:integer"></xs:element>
<xs:element name="Event_manager_name" type="xs:string"></xs:element>
<xs:element name="admin_id" type="xs:integer"></xs:element>
<xs:element name="admin_name" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="Venue" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="V_id" type="xs:integer"></xs:element>
<xs:element name="V_name" type="xs:string"></xs:element>
<xs:element name="V_status" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="Asset" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="Asset_id" type="xs:integer"></xs:element>
<xs:element name="Asset_type" type="xs:string"></xs:element>
<xs:element name="Invoice_id" type="xs:integer"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

=== navvvs/LAB5_DOM_PARSER/event.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="event.xsl"?>
<ChristUniversity xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="event.xsd">
  <User>
    <U_email>navinknaresh@gmail.com</U_email>
    <U_name>Navin</U_name>
    <U_id>1111</U_id>
    <U_gender>Male</U_gender>
    <U_type>Basic</U_type>
    <U_contact>7593485765</U_contact>
  </User>
  <User>
    <U_email>kendallj@gmail.com</U_email>
    <U_name>Kendall</U_name>
    <U_id>1112</U_id>
    <U_gender>Female</U_gender>
    <U_type>Premium</U_type>
    <U_contact>7548585959</U_contact>
  </User>
   <User>
    <U_email>Adithser@gmail.com</U_email>
    <U_name>Adith</U_name>
    <U_id>1113</U_id>
    <U_gender>Female</U_gender>
    <U_type>Premium</U_type>
    <U_contact>754775859</U_contact>
  </User>
   <User>
    <U_email>Suraaaa@gmail.com</U_email>
    <U_name>Suraj</U_name>
    <U_id>1114</U_id>
    <U_gender>Female</U_gender>
    <U_type>Standard</U_type>
    <U_contact>7886582229</U_contact>
  </User>
   <User>
    <U_email>abhiseeeek@yahoo.com</U_email>
    <U_name>Abhiser</U_name>
    <U_id>1115</U_id>
    <U_gender>male</U_gender>
    <U_type>Premium</U_type>
    <U_contact>7547756459</U_contact>
  </User>
   <User>
    <U_email>kendallj@gmail.com</U_email>
    <U_name>Kendall</U_name>
    <U_id>1112</U_id>
    <U_gender>Female</U_gender>
    <U_type>Premium</U_type>
    <U_contact>7548585959</U_contact>
  </User>
  <Ticket>
    <T_id>1000</T_id>
    <T_date>22-12-2000</T_date>
    <T_price>1999</T_price>
  </Ticket>
  <Ticket>
    <T_id>1001</T_id>
    <T_date>07-05-1988</T_date>
    <T_price>3999</T_price>
  </Ticket>
  <Event>
    <Event_id>2000</Event_id>
    <Event_name>Kenny's Stand up</Event_name>
    <Event_type>Comedy</Event_type>
    <Event_time>20:00</Event_time>
  </Event>
  <Event>
    <Event_id>2001</Event_id>
    <Event_name>Suraj's TedxTalk</Event_name>
    <Event_type>Informative</Event_type>
    <Event_time>18:00</Event_time>
  </Event>
  <Staff>
    <Event_manager_id>1000</Event_manager_id>
    <Event_manager_name>Kevin</Event_manager_name>
    <admin_id>1000</admin_id>
    <admin_name>Kelvin</admin_name>
  </Staff>
  <Staff>
    <Event_manager_id>1001</Event_manager_id>
    <Event_manager_name>Jonit</Event_manager_name>
    <admin_id>1001</admin_id>
    <admin_name>Andrew</admin_name>
  </Staff>
  <Venue>
    <V_id>2001</V_id>
    <V_name>Atlas Convention </V_name>
    <V_status>Occupied</V_status>
  </Venue>
    <Venue>
    <V_id>2002</V_id>
    <V_name>Beta Convention </V_name>
    <V_status>Occupied</V_status>
  </Venue>
  <Asset>
    <Asset_id>2000</Asset_id>
    <Asset_type>chair</Asset_type>
    <Invoice_id>1500</Invoice_id>
  </Asset>
    <Asset>
    <Asset_id>2001</Asset_id>
    <Asset_type>table</Asset_type>
    <Invoice_id>1501</Invoice_id>
  </Asset>
  
</ChristUniversity>
